version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: backend
    restart: always
    env_file: .env
    ports:
      - '4000:3001'
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - '8081:80'
    networks:
      - frontend
      
  postgres:
    container_name: postgres
    image: postgres:12
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    restart: always
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
  frontend:


# sudo nano /etc/nginx/sites-available/kupipodariday.student.nomorepartiesco.ru

# символические ссылки
# sudo ln -s /etc/nginx/sites-available/kupipodariday.student.nomorepartiesco.ru /etc/nginx/sites-enabled/kupipodariday.student.nomorepartiesco.ru

#   server {
#         listen 80;

#         server_name kupipodariday.student.nomorepartiesco.ru;

#         location / {
#                 proxy_pass http://localhost:8081;
#                 proxy_http_version 1.1;
#                 proxy_set_header Upgrade $http_upgrade;
#                 proxy_set_header Connection 'upgrade';
#                 proxy_set_header Host $host;
#                 proxy_cache_bypass $http_upgrade;
#         }
# } 


# sudo nano /etc/nginx/sites-available/api.kupipodariday.student.nomorepartiesco.ru


# sudo ln -s /etc/nginx/sites-available/api.kupipodariday.student.nomorepartiesco.ru /etc/nginx/sites-enabled/api.kupipodariday.student.nomorepartiesco.ru

#   server {
#         listen 80;

#         server_name api.kupipodariday.student.nomorepartiesco.ru;

#         location / {
#                 proxy_pass http://localhost:4000;
#                 proxy_http_version 1.1;
#                 proxy_set_header Upgrade $http_upgrade;
#                 proxy_set_header Connection 'upgrade';
#                 proxy_set_header Host $host;
#                 proxy_cache_bypass $http_upgrade;
#         }
# } 